# Generated by Django 5.1 on 2025-01-18 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_emailtemplate_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='content',
            field=models.CharField(max_length=5000),
        ),
    ]
